version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  backend:
    image: harshraisaxena/mean-backend:latest
    container_name: backend
    ports:
      - "3000:8080"
    depends_on:
      - mongo

  frontend:
    image: harshraisaxena/mean-frontend:latest
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
